config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get "home/about" => 'homes#about' ,as: 'about'
  devise_for :users
  resources :books,only:[:create,:index,:show, :edit,:destroy, :update]  do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show,:index, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates:title,
  presence:true
  
  validates:body,
  presence:true,
  length:{maximum:200}
  
  has_many :favorites, dependent: :destroy
  
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
		favorites.exists?(user_id: user.id)
  end
	
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
    
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: { scope: :book_id }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image
  
  has_many :favorites, dependent: :destroy
  
  has_many :book_comments, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true, length: {in: 2..20 }
  validates :introduction, length: {maximum: 50}
  
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path),filename: 'no_image.jpg',content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   
   before_action :authenticate_user!,except:[:top,:about]

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  before_action :authenticate_user!
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 
before_action :ensure_current_user,{only:[:edit,:update]}

  def ensure_current_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:success]="You have created book successfully."
    else
      @books=Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books =Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def edit
    if current_user
      @book = Book.find(params[:id])
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
        redirect_to book_path(@book.id)
        flash[:success]="You have updated book successfully."
    else
      render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :authenticate_user!

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :ensure_current_user,{only:[:edit,:update]}
  def ensure_current_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to user_path(@user.id)
        flash[:success] = "You have updated user successfully."
    else
      render :edit
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name,:profile_image,:introduction)
    end
    
    def book_params
      params.require(:book).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
<table>
  <tbody>
      <% book.book_comments.each do |message| %>
      <tr>
        
        <td>
          <%= link_to user_path(message.user) do %>
            <%= image_tag message.user.get_profile_image(100,100) %><br>
            <%= message.user.name %>
          <% end %>
        </td>
        <td><%= message.comment %></td>
        <td>
          <% if message.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book, message), method: :delete, class: "btn btn-danger pull-right" %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

<%= form_with(model:[book, book_comment],remote: true) do |f| %>
  <%= f.text_area :comment, rows:'10', class: "w-100" %>
  <%= f.submit "送信", class: "btn btn-secondary" %>
<% end %>

app/views/books/_book.html.erb
<!--投稿フォーム-->
<div class="pt-4">
 <h1>New book</h1>
 <%= form_with model: book,local:true do |f| %>
  <div class="form-group">
   <h4 class="py-2">Title</h4>
   <%= f.text_field :title,class:"form-contorol" %>
  </div>
  <div class="form-group">
   <h4 class="py-2">Opinion</h4>
   <%= f.text_area :body,class:"form-control" %>
  </div>

   <%= f.submit "Create Book",class:"btn btn-success" %>

 <% end %>
</div>

app/views/books/edit.html.erb
<!--投稿フォーム-->

<!--エラーメッセージ-->
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:</br>
  <%= @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container pt-3 pb5">
 <div class="row">
  <div class="col-lg-5 mx-auto">

   <h1>Editing Book</h1>
   <%= form_with model: @book,local:true do |f| %>
    <div class="form-group">
     <h4>Title</h4>
     <%= f.text_field :title,class:"form-control" %>
    </div>

    <div class="form-group">
     <h4>Opinion</h4>
     <%= f.text_area :body,class:"form-control" %>
    </div>
    <div class="py-2">
     <%= f.submit "Update Book",class:"btn btn-success" %>
    </div>
     <% if @book.user == current_user %>
      <div class="text-primary pt-2">
       <%= link_to "Show",book_path(@book),class:"btn btn-primary p-1" %>
        |
       <%= link_to "Back",books_path,class:"btn btn-secondary p-1"%>
      </div>
     <% end %>
   <% end %>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3 pr-1">
      <% if @book.errors.any? %>
        <%= @book.errors.count %>error prohibited this obj from being saved:</br>
        <%= @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>

      <%= render "users/user",user:@user %>

      <%= render "books/book",book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %><br>
                <% end %>
              </td>

              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>

              <td><%= book.body %></td>

              <td>コメント数: <%= book.book_comments.count %></td>
              
              <td><%= render "favorites/favorite", book: book %></td>
 
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3 pr-1">
      <%= render "users/user",user:@user %>
      <%= render "books/book",book:@book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
        <div>
          <table class="table">
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(@book.user.id) do %>
                    <%= image_tag @user.get_profile_image(100,100) %>
                    <%= @book.user.name %>
                  <% end %>
                  </a>
                </td>
                <td>
                  <%= link_to @book.title %>
                </td>
                <td><%= @book.body %></td>
                <td>コメント数: <%= @book.book_comments.count %></td>
                <td><%= render "favorites/favorite", book: @book %></td>
                <td>
                  <% if @book.user == current_user %>
                    <%= link_to "Edit",edit_book_path(@book),class:"btn btn-success" %>
                  <% end %>
                </td>
                <td>
                  <% if @book.user == current_user %>
                    <%= link_to "Destroy",book_path(@book),method: :delete,class:"btn btn-danger", data: {confirm: "本当に削除しますか？"} %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
                <%= render "book_comments/comment", book: @book, book_comment: @book_comment %>
        </div>
      </div>
    </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% end %>

app/views/homes/about.html.erb
<dev class="container">
  <div class="row">
    <h1 class="p-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
  </div>
</dev>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          !!
        </h1>
        <p>
          In
          <i class="fas fa-book"></i>
          <strong>Bookers,</strong>
        </p>
        <p>
          you can share and exchange your opinions,inpressinons,and emotions
        </p>
        <p>
          about various books!
        </p>
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3"  %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/552e1d0e68.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-users"></i>
                  Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-book-open"></i>
                  Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path,method: :delete ,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>
                Log out
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to root_path,class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>
                Home
                <% end %>
              </li>
              <Li>
                <%= link_to about_path,class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i>
                About
                <% end %>
              </Li>
              <li>
                <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>
                Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>
                Log in
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
      
        </div>
      </nav>
    </header>

    <!--deviseメッセージ-->

    <span class="text-success">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class:"#{key}") %>
      <% end %>
  </span>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>

</html>

app/views/users/_user.html.erb
<h2>User info</h2>
     
        
    <%= image_tag user.get_profile_image(100,100) %>
      
      
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
      
  <div class="row">
    <%= link_to edit_user_path(user.id),class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

      

app/views/users/edit.html.erb
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-lg-5 mx-auto">
      <h2>User info</h2>
      <div id="error_explanation">
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
          <% end %>
      </div>


        <%= form_with model: @user do |f| %>
        <div class="form-group">
             <%= f.label :Name %>
             <%= f.text_field :name, class: "form-control name" %>
           </div>
           <div class="form-group">
             <%= f.label :image %>
             <%= f.file_field :profile_image,accept: "image/*", class: "form-control-file user_image"  %>
           </div>
           <div class="form-group">
             <%= f.label :Introduction %>
             <%= f.text_area :introduction, class: "form-control introduction" %>
           </div>
           <div class="form-group">
             <%= f.submit 'Update User', class: "btn btn-secondary" %>
           </div>
         <% end %>
       </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3 pr-1">
      <% if @user.errors.any? %>
        <%= @user.errors.count %>error prohibited this obj from being saved:</br>
        <%= @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>

      <%= render "users/user",user:@user %>


      <%= render "books/book",book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
      <table class="table table-resposive">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td>
                <%= image_tag user.get_profile_image(100,100) %>
              </td>

              <td>
                  <%= user.name %>
              </td>

              <td>
                 <%= link_to "Show",user_path(user.id) %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3 pr-1">
      <%= render "users/user",user:@user %>

      <%= render "books/book",book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= image_tag @user.get_profile_image(100,100) %>
                <% end %>
              </td>

              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>

              <td>
                <%= book.body %>
              </td>
              
              <td>
                <%= render "favorites/favorite", book: book %>
              </td>
              
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>